<h2 align="center">Learning Pandas</h2>

### What is Pandas?
<small>Pandas is a Python library for <b>data analysis</b> and <b>manipulation</b>.  
It makes working with tables of data (like Excel sheets or CSV files) very easy.  
Think of it as a tool that helps us clean, explore, and analyze data quickly.</small>

### Main Features :
<small>
<b>Handles tabular data</b> – Rows and columns (like a spreadsheet).<br> 
<b>Data cleaning</b> – Fill missing values, remove duplicates, fix formats.<br>  
<b>Data selection</b> – Easily pick certain rows, columns, or filter data.<br> 
<b>Merging & joining</b> – Combine multiple datasets.<br>
<b>Grouping & aggregation</b> – Summarize data (like average, sum, count).<br>
<b>Time series support</b> – Work with dates and times efficiently.<br>
<b>Note:</b> Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.<br>
</small>
<p>Installation - </p>

```bash
pip install pandas

In [1]:
import pandas as pd

<p>Checking Pandas Version</p>

In [60]:
print(pd.__version__)

3.0.2

<p>A Pandas <b>Series</b> is like a column in a table. It is a one-dimensional array holding data of any type.</p>

In [61]:
arr = [8,9,0]
myvar = pd.Series(arr)
print(myvar)
print(myvar[1])

0    8
1    9
2    0
dtype: int64
9

<p>With the <b>index</b> argument, we can name our own labels.</p>

In [62]:
arr = [3,5,6]
myvar = pd.Series(arr, index = ['X','Y','Z'])
print(myvar)
print(myvar['X'])

X    3
Y    5
Z    6
dtype: int64
3

<p>Data sets in Pandas are usually multi-dimensional tables, called DataFrames. Series is like a column, a DataFrame is the whole table.</p>

In [63]:
data = {'Name' : ['A','B','C'],
        'Age': [22,11,24]}

df = pd.DataFrame(data)
print(df)

# with index argument
df_indexed = pd.DataFrame(data, index = ['x','y','z'])
print(df_indexed)

  Name  Age
0    A   22
1    B   11
2    C   24
  Name  Age
x    A   22
y    B   11
z    C   24

<p>Filtering data</p>

In [64]:
df[df['Age'] > 18]

  Name  Age
0    A   22
2    C   24

<p>New Column Add - </p>

In [65]:
df['Dept'] = ['CSE', 'ME', 'EEE']
print(df)

  Name  Age Dept
0    A   22  CSE
1    B   11   ME
2    C   24  EEE

<p><b>drop()</b> in Pandas - </p>
<p>Syntax : DataFrame.drop(labels=None, axis=0, index=None, columns=None, inplace=False)</p>
<p>Here, labels → Name(s) of row/column to remove. <br>
axis 0 → drop rows and 1 → drop columns. <br>
index → specify row labels directly. <br>
columns → specify column names directly. <br>
inplace = True → modify original DataFrame. False → return new DataFrame (default). </p>

In [66]:
data = {
    "Name": ["A", "B", "C"],
    "Age": [20, 21, 22],
    "City": ["Dhaka", "Chittagong", "Khulna"]
}

df = pd.DataFrame(data)
print(df)

  Name  Age        City
0    A   20       Dhaka
1    B   21  Chittagong
2    C   22      Khulna

<p>Drop a row </p>

In [67]:
df.drop(1, axis = 0)

  Name  Age    City
0    A   20   Dhaka
2    C   22  Khulna

<p>Drop Multiple Rows</p>

In [68]:
df.drop([0,2], axis= 0)

  Name  Age        City
1    B   21  Chittagong

<p>Drop a column</p>

In [69]:
df.drop('Age', axis = 1)

  Name        City
0    A       Dhaka
1    B  Chittagong
2    C      Khulna

<p>Drop multiple columns</p>

In [70]:
df.drop(columns=['Age', 'City'])

  Name
0    A
1    B
2    C

<p>Drop Using <b>index</b> Parameter</p>

In [71]:
df.drop(index=1)

  Name  Age    City
0    A   20   Dhaka
2    C   22  Khulna

<p>In Pandas, the <b>drop()</b> method does not modify the original DataFrame by default; it returns a new DataFrame with the specified rows or columns removed.
To permanently delete data, we must use <b>inplace=True</b> or reassign the result to the original variable.</p>

In [72]:
df

  Name  Age        City
0    A   20       Dhaka
1    B   21  Chittagong
2    C   22      Khulna

In [73]:
df.drop(index=2, inplace=True)

In [74]:
df

  Name  Age        City
0    A   20       Dhaka
1    B   21  Chittagong

<p>Or</p>

In [75]:
delete_permanent = df.drop(index=1)
delete_permanent

  Name  Age   City
0    A   20  Dhaka

<p><b>loc</b> (Label-based indexing) : Selects data using row/column names (labels).</p>

In [76]:
data = {"Name" : ["Asif", "Shariar", "Tashin"],
        "Age": [23,24,22]
        }

df = pd.DataFrame(data, index=['a','b','c'])
print(df)

print('\n')
print(df.loc['c'])
print('\n')
print(df.loc['b', 'Age'])

      Name  Age
a     Asif   23
b  Shariar   24
c   Tashin   22


Name    Tashin
Age         22
Name: c, dtype: object


24

<p><b>iloc</b> (Position-based indexing) : Selects data using index position (0,1,2,...)</p>

In [77]:
print(df.iloc[0])
print(df.iloc[1,1])  # row 1, column 1
# Get first two rows and first one columns
df.iloc[0:2, 0:1]

Name    Asif
Age       23
Name: a, dtype: object
24

      Name
a     Asif
b  Shariar

In [78]:
print(df.iloc[[0,1],[0]])
print('\n')
print(df.loc[['a','c'], ['Name', 'Age']])
print("\n")
print(df[["Name", "Age"]])

      Name
a     Asif
b  Shariar


     Name  Age
a    Asif   23
c  Tashin   22


      Name  Age
a     Asif   23
b  Shariar   24
c   Tashin   22

<p>To save a file in CSV format using Pandas, we use the <b>to_csv()</b> function on a DataFrame.<br>
Basic Syntax - df.to_csv('filename.csv')</p>

In [79]:
data = {
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    "Customer_Name": ["Asif", "Rahim", "Karim", "Shariar", "Tashin", "Rubaba", "Nisa", "Fatin", "Humaira", "Tamim"],
    "Product": ["Laptop", "Mobile", "Headphones", "Tablet", "Camera", "Laptop", "Smartwatch", "Mobile", "Keyboard", "Mouse"],
    "Category": ["Electronics", "Electronics", "Accessories", "Electronics", "Electronics", "Electronics", "Accessories", "Electronics", "Accessories", "Accessories"],
    "Price": [75000, 25000, 2000, 30000, 45000, 80000, 5000, 27000, 1500, 800],
    "Quantity": [1, 2, 3, 1, 1, 1, 2, 1, 4, 5],
    "Total_Amount": [75000, 50000, 6000, 30000, 45000, 80000, 10000, 27000, 6000, 4000],
    "City": ["Dhaka", "Chittagong", "Dhaka", "Khulna", "Rajshahi", "Dhaka", "Sylhet", "Dhaka", "Barisal", "Dhaka"],
    "Payment_Method": ["Card", "Cash", "bKash", "Card", "Cash", "Card", "bKash", "Cash", "Card", "bKash"],
    "Order_Date": [
        "2026-04-01", "2026-04-01", "2026-04-02", "2026-04-02", "2026-04-03",
        "2026-04-03", "2026-04-04", "2026-04-05", "2026-04-05", "2026-04-06"
    ]
}

df = pd.DataFrame(data)
df

,Order_ID,Customer_Name,Product,Category,Price,Quantity,Total_Amount,City,Payment_Method,Order_Date
0,1001,Asif,Laptop,Electronics,75000,1,75000,Dhaka,Card,2026-04-01
1,1002,Rahim,Mobile,Electronics,25000,2,50000,Chittagong,Cash,2026-04-01
2,1003,Karim,Headphones,Accessories,2000,3,6000,Dhaka,bKash,2026-04-02
3,1004,Shariar,Tablet,Electronics,30000,1,30000,Khulna,Card,2026-04-02
4,1005,Tashin,Camera,Electronics,45000,1,45000,Rajshahi,Cash,2026-04-03
5,1006,Rubaba,Laptop,Electronics,80000,1,80000,Dhaka,Card,2026-04-03
6,1007,Nisa,Smartwatch,Accessories,5000,2,10000,Sylhet,bKash,2026-04-04
7,1008,Fatin,Mobile,Electronics,27000,1,27000,Dhaka,Cash,2026-04-05
8,1009,Humaira,Keyboard,Accessories,1500,4,6000,Barisal,Card,2026-04-05
9,1010,Tamim,Mouse,Accessories,800,5,4000,Dhaka,bKash,2026-04-06

<p>Now File Saving - </p>

In [80]:
df.to_csv('ecommerce_orders.csv')
# df.to_csv("ecommerce_orders.csv", index=False)  # if we don't need index

<p>Load the CSV into a DataFrame - </p>

In [2]:
df = pd.read_csv('data.csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

<p>use <b>to_string()</b> to print the entire DataFrame - </p>

In [3]:
df = pd.read_csv('data.csv')
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

<p>To save a DataFrame as an Excel file in Pandas, we use the <b>to_excel()</b> function.</p>

In [5]:
df.to_excel('details.xlsx')
# df.to_excel("details.xlsx", index=False) # if we don't need index

<p><b>Note</b> : We may need an Excel engine like: openpyxl . Install it if needed: </p>

```bash
pip install openpyxl

<p>To export a DataFrame as JSON using Pandas, use the <b>to_json()</b> method. <br>
Basic Syntax : df.to_json("filename.json")</p>

In [84]:
# df.to_json("output.json")
df.to_json('output.json', orient='records')

<p><b>Note</b> : orient='records' . Converts each row into a dictionary (object). <br>
Example: <br>
[
  {"Name": "Asif", "Age": 22},
  {"Name": "Rahim", "Age": 23}
]  </p>

<p>To read a JSON file in Pandas, we use <b>read_json()</b>.</p>

In [4]:
df = pd.read_json('output.json')
print(df)
print("\n")
print(df[["Calories", "Duration"]])

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


     Calories  Duration
0       409.1        60
1       479.0        60
2       340.0        60
3       282.4        45
4       406.0        45
..        ...       ...
164     290.8        60
165     300.0        60
166     310.2        60
167     320.4        75
168     330.4        75

[169 rows x 2 columns]

<p>Multiple logic for filtering - </p>

In [5]:
df[(df["Calories"] > 400) & (df["Duration"] == 60)]

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
35         60    114       140     415.0
53         60    118       151     486.0
55         60    121       146     450.7
56         60    118       121     413.0
116        60    116       141     443.0
144        60    136       170     470.2
149        60    110       150     409.4

<p>In Pandas, joining means combining multiple DataFrames into one.<br>
1. <b>merge()</b> → Database-style join<br>
Syntax : pd.merge(df1, df2, on="column_name", how="type")</p>

In [ ]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Asif", "Shariar", "Tashin"]
})

df2 = pd.DataFrame({
    "ID": [1, 2, 4],
    "Age": [22, 23, 25]
})

merge_df = pd.merge(df1, df2, on = "ID", how="inner")
merge_df

   ID     Name  Age
0   1     Asif   22
1   2  Shariar   23

<p>2. <b>concat()</b> → Stacking data</p>

In [ ]:
# Row-wise (default)
pd.concat([df1, df2])

   ID     Name   Age
0   1     Asif   NaN
1   2  Shariar   NaN
2   3   Tashin   NaN
0   1      NaN  22.0
1   2      NaN  23.0
2   4      NaN  25.0

In [ ]:
# Column-wise
pd.concat([df1, df2], axis=1)

   ID     Name  ID  Age
0   1     Asif   1   22
1   2  Shariar   2   23
2   3   Tashin   4   25

<h3 align="center">Cleaning Data </h3>
<p>Data cleaning means fixing bad data in your data set.<br>
Bad data could be: 1. Empty cells 2. Data in wrong format 3. Wrong data 4. Duplicates</p>

<p>1. Cleaning Empty Cells - <br>
Empty cells can potentially give us a wrong result when we analyze data.<br>

1. <b>Remove Rows</b> <br>
One way to deal with empty cells is to remove rows that contain empty cells. This is usually OK, since data sets can be very big, and removing a few rows will not have a big impact on the result.<br>

2. <b>Replace Empty Values</b> <br>
Another way of dealing with empty cells is to insert a new value instead. This way you do not have to delete entire rows just because of some empty cells.<br>

3. <b>Replace Using Mean, Median, or Mode</b><br>
A common way to replace empty cells, is to calculate the mean, median or mode value of the column.</p>

In [58]:
df = pd.read_csv('raw_data.csv')
df.shape

(891, 12)

<p><b>Note : df.shape</b> is a DataFrame attribute that returns the dimensions (size) of the dataset.</p>

<p>1</p>

In [50]:
# df.dropna()
# df

<p><b>Note : </b> By default, the <b>dropna()</b> method returns a new DataFrame, and will not change the original.<br>

If we want to change the original DataFrame, use the <b>inplace = True</b> argument. Like, <b>dropna(inplace = True)</b>. The <b>dropna(inplace = True)</b> will NOT return a new DataFrame, but it will remove all rows containing NULL values from the original DataFrame.</p>

In [39]:
# check data types
# Method 1
# df.dtypes
# Method 2
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [65]:
# for checking empty
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

<p>2</p>

In [42]:
# df.fillna(130) # data types check (must same to fill)

# df.fillna({'Age' : 130}, inplace= True) # Replace Only For Specified Columns

<p><b>Note : </b>The <b>fillna()</b> method allows us to replace empty cells with a value. </p>

<p>3</p>

In [56]:
# x = df["Age"].mean()
# df.fillna({"Age" : x}, inplace= True)
# df.to_csv("m.csv")



# x = df['Age'].mode()
# print(x)

# df.fillna({"Age" : x}, inplace=True)
# df.to_csv("m.csv")



## similarly use median()

<p>For Data in Wrong Format check - > <a href="https://www.w3schools.com/python/pandas/pandas_cleaning_wrong_format.asp">Click</a> and for Wrong Data check -> <a href="https://www.w3schools.com/python/pandas/pandas_cleaning_wrong_data.asp">Click</a>

<p>4. Discovering and Removing Duplicates</p>

In [68]:
print(df.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

<p><b>Note : </b>The <b>duplicated()</b> method returns a Boolean values for each row. It returns <b>True</b> for every row that is a duplicate, otherwise <b>False</b>.</p>

<p>To remove duplicates, use the <b>drop_duplicates()</b> method.</p>

In [69]:
# Remove all duplicates
df.drop_duplicates(inplace = True)

<p><b>df.duplicated().sum()</b> → counts the number of duplicate rows in the DataFrame (excluding the first occurrence).</p>

In [72]:
df.duplicated().sum()

np.int64(0)

<p><b>head()</b> - View the first few rows of a DataFrame</p>

In [74]:
df.head()  # first 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [75]:
df.head(10) # first 10 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

<p><b>tail() - </b>View the last few rows</p>

In [76]:
df.tail()  # last 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [77]:
df.tail(10)  # last 10 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [78]:
df.sum()

PassengerId                                               397386
Survived                                                     342
Pclass                                                      2057
Name           Braund, Mr. Owen HarrisCumings, Mrs. John Brad...
Sex            malefemalefemalefemalemalemalemalemalefemalefe...
Age                                                     21205.17
SibSp                                                        466
Parch                                                        340
Ticket         A/5 21171PC 17599STON/O2. 31012821138033734503...
Fare                                                  28693.9493
Cabin          C85C123E46G6C103D56A6C23 C25 C27B78D33B30C52B2...
Embarked       SCSSSQSSSCSSSSSSQSSCSSQSSSCSQSCCQSCSCSSCSSCCQS...
dtype: object