In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {
    "Name" : ["Asif", "Nisa", "Shariar", np.nan],
    "Age" : [23, 21, np.nan, 24],
    "Salary" : [50000, 30000, 30000, np.nan]
}

df = pd.DataFrame(data)

In [4]:
df

      Name   Age   Salary
0     Asif  23.0  50000.0
1     Nisa  21.0  30000.0
2  Shariar   NaN  30000.0
3      NaN  24.0      NaN

In [7]:
df.fillna({
    "Name" : "Unknown",
    "Age" : df["Age"].mean(),
    "Salary" : 0
}, inplace = True)

      Name        Age   Salary
0     Asif  23.000000  50000.0
1     Nisa  21.000000  30000.0
2  Shariar  22.666667  30000.0
3  Unknown  24.000000      0.0

In [8]:
df

      Name        Age   Salary
0     Asif  23.000000  50000.0
1     Nisa  21.000000  30000.0
2  Shariar  22.666667  30000.0
3  Unknown  24.000000      0.0

In [9]:
df.dtypes

Name          str
Age       float64
Salary    float64
dtype: object

In [10]:
df["Age"] = df["Age"].astype(int)

In [11]:
df.dtypes

Name          str
Age         int64
Salary    float64
dtype: object

In [21]:
df

      Name  Age   Salary
0     Asif   23  50000.0
1     Nisa   21  30000.0
2  Shariar   22  30000.0
3  Unknown   24      0.0

In [39]:
sorted_table = df.sort_values(by = "Salary", ascending = True)  # ascending = False for descending
sorted_table

      Name  Age   Salary
3  Unknown   24      0.0
1     Nisa   21  30000.0
2  Shariar   22  30000.0
0     Asif   23  50000.0

In [12]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.split(arr, 5)  # Splits the array arr into 5 equal parts

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [27]:
arr = np.array([6,3,8,0])
print(np.sort(arr))
print(np.sort(arr)[::-1])  # reversing sorting

[0 3 6 8]
[8 6 3 0]

<p><b>np.searchsorted(sorted_array, value)</b> finds the index where a value should be inserted in a sorted array to keep it sorted</p>

In [31]:
arr = np.array([20,30,40,90])  
pos = np.searchsorted(arr, 15)
pos

# Note : Array must be sorted

np.int64(0)

<p><b>np.where(...)</b> - Returns the positions (indices) where condition is True. <b>np.where</b> returns a tuple</p>

In [34]:
arr = np.array([201, 198, 77, 76, 29, 3])
even = np.where (arr % 2 == 0)
even

(array([1, 3]),)